### ISSUE TITLE
AttributeError: type object 'dict' has no attribute '__args__'

### ISSUE THREAD

**Issue by jjuu** [lidatong/dataclasses-json#114]
```
@dataclass_json
@dataclass
class SampleModel:
    id: str = None
    data_dict: dict = None

data = {
        'id': 2,
        'data_dict': {
            'a': 1,
            'b': 'world'
        }
    }

sm = SampleModel.from_dict(data, infer_missing=True)
print(sm)
```

I have dict attribute which I want to change to dict as it is.

> Traceback (most recent call last):
>   File "dict_to_dataclass/sample.py", line 58, in <module>
>     sm = SampleModel.from_dict(data, infer_missing=True)
>   File "dataclasses_json\api.py", line 88, in from_dict
>     return _decode_dataclass(cls, kvs, infer_missing)
>   File "dataclasses_json\core.py", line 161, in _decode_dataclass
>     infer_missing)
>   File "dataclasses_json\core.py", line 200, in _decode_generic
>     k_type, v_type = type_.__args__
> AttributeError: type object 'dict' has no attribute '__args__'

But give me an exception.
Any solution?

**Comment by jjuu** [comment]
python version 3.7

**Comment by kato-m** [comment]
I am struggeling wth the same problem. Is there any workaround ot fix?

**Comment by jjuu** [comment]
You'd better to use dataclass_factory, which source code is not confuse.
