### ISSUE TITLE
AttributeError when decoding to Optional[str]?

### ISSUE THREAD

**Issue by gmolau** [lidatong/dataclasses-json#12]
I've been getting an AttributeError when trying to decode a dict to a dataclass with optional str arguments, i.e. something like:

```python
@dataclass
class A:
    a: Optional[str] = None
```

Stepping through this with PDB I've noticed that `_is_supported_generic()` evaluates to `True` for str, causing [this branch](https://github.com/lidatong/dataclasses-json/blob/f89db238150e12f17853649856194586945c8040/dataclasses_json/core.py#L90) in dataclasses_json.core to call `_decode_generic()` with `type_ = str` and then failing on [line 73](https://github.com/lidatong/dataclasses-json/blob/f89db238150e12f17853649856194586945c8040/dataclasses_json/core.py#L73) because `str` has no `__args__` attribute.

This example should illustrate the problem more clearly:

```python
In [1]: import dataclasses_json, typing

In [2]: dataclasses_json.core._decode_generic(typing.Optional[str], 'foo', False)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-ef8bcdf59b9e> in <module>()
----> 1 dataclasses_json.core._decode_generic(typing.Optional[str], 'foo', False)

<project_dir>/venv/lib/python3.7/site-packages/dataclasses_json/core.py in _decode_generic(type_, value, infer_missing)
     89             res = _decode_dataclass(type_arg, value, infer_missing)
     90         elif _is_supported_generic(type_arg):
---> 91             res = _decode_generic(type_arg, value, infer_missing)
     92         else:
     93             res = value

<project_dir>/venv/lib/python3.7/site-packages/dataclasses_json/core.py in _decode_generic(type_, value, infer_missing)
     71         # type_arg is a typevar we need to extract the reified type information
     72         # hence the check of `is_dataclass(value)`
---> 73         type_arg = type_.__args__[0]
     74         if is_dataclass(type_arg) or is_dataclass(value):
     75             xs = (_decode_dataclass(type_arg, v, infer_missing) for v in value)

AttributeError: type object 'str' has no attribute '__args__'
```

Is this a bug, or am I misunderstanding something?

**Comment by lidatong** [comment]
thanks for catching this and providing the detailed issue summary. yep this is a bug where `str` is incorrectly passing the `_is_supported_generic` check. fix in #16
