### ISSUE TITLE
TypeError: make_instance() got an unexpected keyword argument 'many'

### ISSUE THREAD

**Issue by kkbblzq** [lidatong/dataclasses-json#136]
dataclasses-json==0.3.1
marshmallow==3.0.1
marshmallow-enum==1.5.1
python 3.7.3
'''
@dataclass_json
@dataclass
class Person:
    name: str
    age: int

if __name__ == '__main__':
    data = [{'name': 'zs', 'age': 1}, {'name': 'ls', 'age': 2}]
    Person.schema().load(data, many=True)
'''

raise TypeError 
TypeError: make_instance() got an unexpected keyword argument 'many'

**Comment by yukihiko-shinoda** [comment]
Duplicate of #135
