### ISSUE TITLE
Possible issue with timestamp serialization

### ISSUE THREAD

**Issue by stevenbedrick** [lidatong/dataclasses-json#146]
Apologies if this is a known limitation, but I have run into an issue when using the `.schema().dumps()` functionality. I have encountered an issue with serialization of dataclasses with optional timestamp fields whose value is `None` at the time of serialization. The `.to_json()` method works just fine in this case, but I believe that there is [a bug in line 25 of `dataclasses_json/mm.py`](https://github.com/lidatong/dataclasses-json/blob/03dc2f9bc04c24cfb5d3eded63f6c4176d4779bf/dataclasses_json/mm.py#L25) that is encountering problems when the `value` in question is `None`. 

I have put together a small example script illustrating the issue [here](https://gist.github.com/stevenbedrick/d05970da1a21b60c3cd8fc421d37e90e).

One possible fix would just be to add a check for `None` to the `_TimestampField._serialize()` method; from my read of the [calling code in Marshmallow](https://github.com/marshmallow-code/marshmallow/blob/dev/src/marshmallow/fields.py#L325), it looks like it's expecting field-specific serializers to be able to handle `None` values in this sort of situation.

**Comment by FaraSeer** [comment]
Hi! If I understood correctly, then the bug is already described here: #108

**Comment by stevenbedrick** [comment]
Yup, that's definitely the same bug. Sorry for the duplicate!
