### ISSUE TITLE
globally change default encoder/decoder

### ISSUE THREAD

**Issue by npgm** [lidatong/dataclasses-json#154]
Our APIs return and consume iso-formatted datetimes - it would be great if I could globally  change the encoder/decoder for this, instead of having to configure at the per field level. Alternatively, if the @dataclass_json annotation provided type specific encoder/decoder overrides I could create our own internal annotation wrapping dataclass_json with the default config.

**Comment by lidatong** [comment]
Apologies for the lengthy delay responding. Thanks for your note, this feature is on the radar, see #139.
