### ISSUE TITLE
Problems when dataclass is also mapped in sqlalchemy 

### ISSUE THREAD

**Issue by eblis** [lidatong/dataclasses-json#158]
I'm trying to get dataclasses-json to work with sqlalchemy but have had little success so far.
I think both dataclasses-json and sqlalchemy are trying to mess with the class definitions and it's breaking the conversion between JSON and objects.

Python 3.8 on Windows
dataclasses-json==0.3.6
SQLAlchemy==1.3.11

```
from dataclasses_json import LetterCase, dataclass_json
from sqlalchemy import Table, Column, Integer, String, Float, ForeignKey
from sqlalchemy.orm import mapper, relationship, backref

@dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
class Address():
    street: str
    city: str
    id: int = None

@dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
class User():
    first_name: str
    last_name: str
    address: Address
    id: int = None

addressTable = Table("address", metadata,
                     Column("id", Integer, primary_key=True),
                     Column("street", String),
                     Column("city", String),
                     Column("user_id", Integer, ForeignKey("user.id"))
                     )

mapper(Address, addressTable, properties={
})

userTable = Table("user", metadata,
                  Column("id", Integer, primary_key=True),
                  Column("firstName", String),
                  Column("lastName", String),
                  )

mapper(User, userTable, properties={
    "address": relationship(Address, backref=backref(userTable.c.id, uselist=False))
})
```

I'm trying to parse the following json
```
{
  "firstName": "first name",
  "lastName": "last name",
  "address": {
    "street": "street name",
    "city": "city name"
  }
}
```

But when I try to call `User.from_json(body.decode("utf-8"), infer_missing=True)` i get the following exception
```
  File "example_python-3XnK4UKl\lib\site-packages\sqlalchemy\orm\relationships.py", line 919, in instrument_class
    attributes.register_descriptor(
  File "example_python-3XnK4UKl\lib\site-packages\sqlalchemy\orm\attributes.py", line 1876, in register_descriptor
    manager.instrument_attribute(key, descriptor)
  File "example_python-3XnK4UKl\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 240, in instrument_attribute
    self.install_descriptor(key, inst)
  File "example_python-3XnK4UKl\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 296, in install_descriptor
    setattr(self.class_, key, inst)
TypeError: attribute name must be string, not 'Column'
```
If I remove the sqlalchemy mapping initializations (just don't call them) then it works as expected, i get a `User` instance.

**Comment by TalyGin** [comment]
I've got similar problem, any updates on it? How it supposed to be used with sqlalchemy?

**Comment by eblis** [comment]
I used 2 separate classes, one for the @dataclass annotation, one for the SqlAlchemy one

**Comment by lavahot** [comment]
> I used 2 separate classes, one for the @DataClass annotation, one for the SqlAlchemy one

How did you do this? How do the two classes relate to each other?

**Comment by lidatong** [comment]
So I investigated your example, and made this small change:

```python
# @dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
class Address:
    street: str
    city: str
    id: int = None

Address('street_name', 'city_name')
```

Notice that I have commented out `@dataclass_json` from `Address` and `User`, and I am simply attempting to initialize `Address` normally as a `dataclass`. I get the same exception as above

I haven't used SQLAlchemy too extensively, but this suggests to me this is an issue with using `SQLAlchemy` and `dataclasses` together (unrelated to this library). I'd take look at `SQLAlchemy` API docs and see if they have an explanation of how to use it together
