### ISSUE TITLE
field_name not working in combination with letter_case

### ISSUE THREAD

**Issue by aliebig** [lidatong/dataclasses-json#160]
When combing @dataclass_json(letter_case=LetterCase.CAMEL) with "field_name" config, the "field_name" configuration has no effect.  

### Run the following  code
```python
from dataclasses import dataclass, field

from dataclasses_json import dataclass_json, config, LetterCase

@dataclass
@dataclass_json(letter_case=LetterCase.CAMEL)
class ExampleClass:
    identifier: str = field(
        metadata=config(
            field_name="id"
        ))
    other_field: str

print(ExampleClass("id_value", "other_value").to_dict())

```
### Expected output:
**{'id': 'id_value', 'otherField': 'other_value'}**

### Observed output:
**{'identifier': 'id_value', 'otherField': 'other_value'}**
The effect is the same for other LetterCase values

### Environment:
python: 3.8
dataclasses-json: 0.3.6

**Comment by lidatong** [comment]
thank you for reporting this and providing the example. should be addressed by #209 (thanks @sumnerevans)
