### ISSUE TITLE
Clarify differences in usage & code analysis between decorator and mixin

### ISSUE THREAD

**Issue by synrg** [lidatong/dataclasses-json#161]
Please clarify in your documentation the differences in usage & support by code analysis tools (e.g. pylint) between the decorator approach and mixin approach. This is regarding this point in the README:

> Pick whichever approach suits your taste. The differences in implementation are invisible in usage.

My first problem with the decorator was that without `# pylint: disable=no-member` on each `User.from_dict(record)` in my code, pylint complained about `User` not having that member. Switching to the mixin approach solved this.

In discussion with another developer, he pointed out that type hinting wouldn't work either with the decorator approach, as untyped decorators are assumed to return the callable with an identical interface. On the other hand, it could be supported with the mixin approach.

**Comment by lidatong** [comment]
Hi, thanks for the suggestion. Technically this library doesn't officially support `typing`. I myself have not kept up with Python's `typing` developments and attribute credit to 3rd party contributors for the `typing` annotations. However, I think you have a fair point as `typing` gains increasing traction. I have updated the docs.
