### ISSUE TITLE
Can not define optional/any nested type with schema

### ISSUE THREAD

**Issue by RunOrVeith** [lidatong/dataclasses-json#166]
Consider the following example:

```python
from dataclasses_json import dataclass_json
from dataclasses import dataclass
from typing import Dict, Any

@dataclass_json
@dataclass
class Test:
    x: Dict[str, Any]

Test.schema().load({"x": {"test": None})
```

Results in `marshmallow.exceptions.ValidationError: {'x': defaultdict(<class 'dict'>, {'test': {'value': ['Field may not be null.']}})}`, even though `Any` includes `None` as a valid value.

The same happens when you define `x: Dict[str, Optional[Any]]`.

I am not sure what the desired behavior here is, especially with the fact that [Any is not the same as Optional[Any]](https://github.com/python/mypy/issues/3138).
I have a  solution for both cases in the enclosed pull request

**Comment by obi1kenobi** [comment]
Assuming this should be closed since #167 was merged?
