### ISSUE TITLE
Behaviour of all capital JSON fields when using Camel LetterCase

### ISSUE THREAD

**Issue by nazariyv** [lidatong/dataclasses-json#170]
```
@dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
class Person:
    name: str = field(default="", metadata=config(field_name="NAME"))

Person.from_dict({"NAME": "Ray Dalio"})
```

expected:
```
Person(name="Ray Dalio")
```

actual:
```
Person(name='')
```

**Comment by nazariyv** [comment]
I have printed out this part: https://github.com/lidatong/dataclasses-json/blob/master/dataclasses_json/core.py#L78, and I can see that it is all lower case, i.e. I should change the above to?:

```
@dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
class Person:
    name: str = field(default="", metadata=config(field_name="name"))

Person.from_dict({"NAME": "Ray Dalio"})
```

but this doesn't fix the issue either

**Comment by nazariyv** [comment]
but doing this:

```
@dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
class Person:
    name: str = field(default="", metadata=config(field_name="NAME"))

Person.from_dict({"name": "Ray Dalio"})
```

works. ermmm

**Comment by nazariyv** [comment]
This:

```
            k = letter_case(k) if letter_case is not None else k
            print(f"Old key: {original_key}, New key: {k}")
```

produces such a log:

```
Old key: price, New key: price
Old key: measure_type, New key: measureType
Old key: price_period_type, New key: pricePeriodType
Old key: fund_yield, New key: fundYield
Old key: price_obj, New key: priceObj
Old key: isin, New key: isin
Old key: ocf, New key: ocf
```

I think I might have named them incorrectly, clearly the thing on the left is new key and the thing on the right is the old key. 

So, looking at the above log, we can say that the right hand side for `isin` and `ocf` is incorrect. Basically, they should be all capital there on the right-hand side.

**Comment by nazariyv** [comment]
Printing the `kvs` of `_encode_overrides` also reveals something curious, the nested dataclasses' fields are camelCase, while the outer's `underscored` (note that all of my dataclasses are marked `letter_case=LetterCase.CAMEL`):

```
kvs: {'price_obj': {'asOfDate': '', 'price': nan, 'measureType': nan, 'pricePeriodType': {'measureDesc': ''}, 'fundYield': {'pricePeriodDesc': ''}}, 'isin': '', 'ocf': nan, 'performance_since_inception': nan, 'annual_total_return1yr': nan, 'annual_total_return3yr': nan, 'annual_total_return5yr': nan, 'annual_total_return10yr': nan, 'performance1month': nan, 'performance3month': nan, 'performance6month': nan, 'performance_ytd': nan, 'perf_as_of_data': datetime.datetime(1970, 1, 1, 0, 0, tzinfo=<UTC>), 'dist_segment_share_class_desc': '', 'fund_name_from_ecs': '', 'inceptiondate': '', 'bench_mark': '', 'bloomberg': '', 'currency': '', 'sedol': ''}
```

looks to me like the best "solution" for now is to simply disable the camel case options.

**Comment by ToucanBran** [comment]
I can confirm the same thing is still happening. For example:

```
@dataclass_json(letter_case=LetterCase.PASCAL)
@dataclass
class Dog:
    color: str = field(metadata=(config(field_name="coat_color")))
    breed: str = None

brown_dog = Dog(color="brown")

print(brown_dog.to_json())

```
will show `{"coat_color": "brown", "Breed": "yorkie"}`

**Comment by matt035343** [comment]
I have tested this in the newest version. It seems to be no longer an issue. If you still think this is an issue, please reopen and add more details, such as python version, dataclasses-json version, etc.
