### ISSUE TITLE
A way to enhance json encoder

### ISSUE THREAD

**Issue by imbolc** [lidatong/dataclasses-json#177]
I found the lib can't encode `pahtlib.Path` at the moment. I looked to the code with a hope to find there something like `functools.singledispatch` so I can just register `Path` there. But there's just subclassing of `json.JSONEncoder`. I didn't dig deep into the the code, is there a reason for not using `singledispatch`?

**Comment by lidatong** [comment]
Hi, you can use the `encoder` config option. Please see this [extending](https://lidatong.github.io/dataclasses-json/#extending) section of the docs
