### ISSUE TITLE
v0.3.7 introduced breaking change - default arg support

### ISSUE THREAD

**Issue by nyurik** [lidatong/dataclasses-json#179]
This code runs fine with v0.3.6, but breaks in v0.3.7 (which is something I would expect of the major version, not patch):

```python
from dataclasses import dataclass
from dataclasses_json import dataclass_json

@dataclass
@dataclass_json
class MyClass:
    foo: int = 0

v1 = MyClass()
v2 = MyClass(foo=1)    #  <---  TypeError: MyClass() takes no arguments
```

To test, copy/paste the above code after running one of these:
```
docker run --rm -it python:3.8 sh -c 'pip install -I dataclasses-json==0.3.6 && python'
docker run --rm -it python:3.8 sh -c 'pip install -I dataclasses-json==0.3.7 && python'
```

**Comment by lidatong** [comment]
Hi, it looks like you reversed the order of the decorators. `@dataclass` should be applied before `@dataclass_json`

**Comment by nyurik** [comment]
@lidatong I don't understand what you mean. The code was working fine in 0.3.6, and it no longer works in 0.3.7.  That's a breaking change, isn't it?

**Comment by lidatong** [comment]
Sorry, let me try to be more clear.

The library documentation states that `dataclass_json` must be applied after `dataclass` ([see this](https://lidatong.github.io/dataclasses-json/#approach-1-class-decorator)). It's not a breaking change to the API, as it was never intended to be supported. It's analogous to using a private variable that gets removed
