### ISSUE TITLE
Pipenv gets broken

### ISSUE THREAD

**Issue by Mulugruntz** [lidatong/dataclasses-json#18]
Pipenv get broken when using `dataclasses-json`.
In the `setup.py`, replacing `marshmallow>=3.0.0b13` by `marshmallow==3.0.0b13` should make it work.
And it's safer anyway (if there's a non-backward compatible version of marshmallow that gets released, it will currently break dataclasses-json.

**Comment by lidatong** [comment]
Hi, thanks for calling this out and the corresponding fix!
