### ISSUE TITLE
V 0.4.1 - Custom encoding sometimes fail in unittests

### ISSUE THREAD

**Issue by sdupere-git** [lidatong/dataclasses-json#192]
We had to revert back to version 0.3.8 since 0.4.1 would have really weird behaviors,

0.4.1 would sometime do the following:
* Ignore fields with custom encoding and encode fields with their default encoding (datetime becoming float, bytes becoming lists, etc...).
* Fail to find the none-generic constructor of a typing.List (Throws an exception for using a List constructor instead of list)

The failures were frequent, but intermittent... In our unit tests, sometime the encoding would work, sometime not...same for the decoding of a List...sometime it would work, sometime not... Did not find a clear reason why it happened.

Rolling back to 0.3.8 fixed everything.

We think the issue might be related to the addition of caching.

**Comment by lidatong** [comment]
Hi, I'm sorry for the issues with `0.4.1`. I've reverted the caching changes in the latest release `0.4.2`. Let me know if that resolves your issues.

**Comment by sdupere-git** [comment]
0.4.2 works fine.

Thank you for the quick fix :)

Really appreciated!
