### ISSUE TITLE
Datetime without time zone is loaded wrongly [bug]

### ISSUE THREAD

**Issue by AndreyMZ** [lidatong/dataclasses-json#193]
### Steps to reproduce
Run the following tests by [pytest](https://pypi.org/project/pytest/) (e.g. with environment variable `TZ=Europe/London`):
~~~py
from dataclasses import dataclass
from datetime import datetime, timezone

from dataclasses_json import DataClassJsonMixin

@dataclass
class Foo(DataClassJsonMixin):
    f: datetime

def test_with_tz():
    foo_obj = Foo(f=datetime.now(tz=timezone.utc))
    assert Foo.from_json(foo_obj.to_json()) == foo_obj

def test_without_tz():
    foo_obj = Foo(f=datetime.now())
    assert Foo.from_json(foo_obj.to_json()) == foo_obj
~~~

#### Actual result
`test_with_tz` passed.
`test_without_tz` failed:
~~~
Expected :Foo(f=datetime.datetime(2020, 3, 13, 7, 8, 38, 599463))
Actual   :Foo(f=datetime.datetime(2020, 3, 13, 7, 8, 38, 599463, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600), 'ope')))
~~~

#### Expected result
Both tests passed.

**Comment by lidatong** [comment]
Hi, thanks for reporting this issue (and the others). I appreciate providing the unit test examples to help detail the problem.

This particular issue is actually not a bug, as noted in the docs:

> As specified in the datetime docs, if your datetime object is naive, it will assume your system local timezone when calling .timestamp(). JSON numbers corresponding to a datetime field in your dataclass are decoded into a datetime-aware object, with tzinfo set to your system local timezone. Thus, if you encode a datetime-naive object, you will decode into a datetime-aware object. This is important, because encoding and decoding won't strictly be inverses.

Let me know if that helps, thanks again

**Comment by AndreyMZ** [comment]
That's my fault, I didn't notice this docs. Thank you for the answer!
