### ISSUE TITLE
datetime and/or overriding serializers

### ISSUE THREAD

**Issue by dodgyville** [lidatong/dataclasses-json#20]
Hi, great library. 

It works except I can't serialise a datetime object on my dataclass. Is there a way to pass in my own serialiser?

EDIT: I can pass a fallback function using "default" 
```
dataclass_obj.to_json(default=json_serial)

def json_serial(obj):
    """JSON serializer for objects not serializable by default json code"""

    if isinstance(obj, (datetime, date)):
        return obj.isoformat()
    raise TypeError ("Type %s not serializable" % type(obj))
```

**Comment by lidatong** [comment]
yep, that's what the `default` parameter is there for (it mirrors the API of the built-in `json` module)
