### ISSUE TITLE
Omitting fields when serializing

### ISSUE THREAD

**Issue by arusahni** [lidatong/dataclasses-json#200]
Is it possible to omit fields when `to_dict` or `to_json` is invoked?  My use-case is I have fields with sensitive information that I only want available to the internal parts of my application, and would like to ensure they're never pushed to my end-users.

Right now, I'm accomplishing it by overriding `to_dict` as follows:

```python
@dataclass
class MyObject(DataClassJsonMixin):
    """An object."""

    id_: uuid.UUID = field(metadata=config(field_name="id"))
    name: str
    secret: str
    another_secret: str

    def to_dict(  # type: ignore[override]
        self, omit_sensitive=True, **kwargs
    ) -> Dict[str, "dataclasses_json.core.Json"]:
        """Serialize the dataclass, with an optional ability to omit sensitive/internal fields."""
        serialized = super().to_dict(**kwargs)
        if omit_sensitive:
            for field_name in list(serialized.keys()):
                if field_name in ("secret", "another_secret"):
                    del serialized[field_name]
        return serialized
```

Ideally, this would be something I could define as part of the `field()`.  Is this currently possible with dataclass-json, and, if not, would this be something that you would consider for future functionality?

**Comment by jcmuddle** [comment]
I've got a similar need, in my case I have an API that will return an error if I pass None instead of omitting the optional argument. Here is my solution.

`def _asdict(obj, encode_json=False, drop_optional=False):
    """
    Convert an obj to a dictionary.
    
    A re-implementation of `asdict` (based on the original in the `dataclasses`
    source) to support arbitrary Collection and Mapping types.
    """
    if _is_dataclass_instance(obj):
        result = []
        for field in fields(obj):
            if field.default is None:
                field_optional = True
            else:
                field_optional = False
            value = _asdict(
                getattr(obj, field.name),
                encode_json=encode_json,
                drop_optional=drop_optional,
            )
            if drop_optional and field_optional and value is None:
                continue
            result.append((field.name, value))

        result = _handle_undefined_parameters_safe(
            cls=obj, kvs=dict(result), usage="to"
        )
        return _encode_overrides(
            dict(result), _user_overrides_or_exts(obj), encode_json=encode_json
        )
    elif isinstance(obj, Mapping):
        return dict(
            (
                _asdict(k, encode_json=encode_json, drop_optional=drop_optional),
                _asdict(v, encode_json=encode_json, drop_optional=drop_optional),
            )
            for k, v in obj.items()
        )
    elif (
        isinstance(obj, Collection)
        and not isinstance(obj, str)
        and not isinstance(obj, bytes)
    ):
        return list(
            _asdict(v, encode_json=encode_json, drop_optional=drop_optional)
            for v in obj
        )
    else:
        return copy.deepcopy(obj)`
Perhaps this can be incorporated into this library.

**Comment by RunOrVeith** [comment]
I don't think dropping everything that has `None` as default is the best solution to this problem.
I think a better solution would add something like 
```python
secret_stuff: Optional[str] = field(default=None, metadata=config(drop_on_export=True))
```

**Comment by jcmuddle** [comment]
Thanks @RunOrVeith, that is a far more elegant solution. I wasn't aware of the `field` function or its metadata parameter.

**Comment by arusahni** [comment]
I filed a PR that can address both these use-cases.

An example of how it may address @jcmuddle's:

```python
secret_stuff: Optional[str] = field(default=None, metadata=config(encode_action=lambda k, v: v is None))
```

**Comment by lidatong** [comment]
Hi, thanks to all for raising the issue and the discussion above!

Both these use-cases make sense to me, though I'd favor simply calling the parameter `exclude` which expects a predicate

I think #221 already covers this functionality (thanks @arusahni), will add comments to the PR thread

**Comment by jcmuddle** [comment]
Thank you @arusahni, this worked perfectly for my use-case.
Thank you @lidatong for the great package.
