### ISSUE TITLE
Pathlib support

### ISSUE THREAD

**Issue by illeatmyhat** [lidatong/dataclasses-json#202]
It's annoying to define this for every path. It ought to be supported natively.
```
@dataclass_json
@dataclass
class Foo:
    file_path: Path = field(metadata=config(encoder=str, decoder=Path))
```

**Comment by dalek-who** [comment]
Following  #139, a possibility solution is global register `Path` for `dataclasses_json` manually:

```python 
import dataclasses_json.cfg
from pathlib import Path

dataclasses_json.cfg.global_config.encoders[Path] = str
dataclasses_json.cfg.global_config.decoders[Path] = Path  # is this necessary?

@dataclass_json
@dataclass
class Foo:
    file_path: Path
```

**Comment by george-zubrienko** [comment]
Closing as the question was answered

**Comment by pfsalminen** [comment]
@george-zubrienko I have recently encountered this issue. Since there is support for other complex builtins (Decimal, UUID, Datetime), is there a reason not to support this? I would be interested in implementing it.
