### ISSUE TITLE
Wrong serialisation due to overrides not working 

### ISSUE THREAD

**Issue by eliwe** [lidatong/dataclasses-json#205]
Hi,

I have a dataclass like:
`@dataclass
class Foo(dataclasses_json.DataClassJsonMixin):
    a: int = field(metadata=dataclasses_json.config(encoder=lambda i: str(i), decoder=lamdba s: int(s)))`

Sometimes the encoedr function is not called when calling to_dict on an instance of Foo.
I failed to write a test program that reproduces this consistently but have a theory.
In core.py _asdict obj, which is an instance, is passed to _user_overrides_or_exts which expects a class.
This works correctly as everything used also works on an instances.
But the function is cached on the id of the object:
`@cached(cache=_user_overrides_cache, key=id)
`
For classes its a good assumption (most code doesn't generate classes at runtime).
But for instances this is bad as the id gets reused and the cache can become stale. This can lead the problem I described above as the returned dict will be for a different cls.

The fix is to pass the class instead of the instance.

Thanks.

**Comment by eblis** [comment]
Wasn't the cache removed in the last version ?

**Comment by eliwe** [comment]
You are correct. 
Sorry.
I was on 0.4.1
