### ISSUE TITLE
support date type

### ISSUE THREAD

**Issue by MichaelAzimov** [lidatong/dataclasses-json#211]
Is there some sort of default support for date type (like for datetime), and if not would it be useful if I implement one and create a PR?

**Comment by kevinmu** [comment]
@MichaelAzimov  is something like this what you are looking for? https://github.com/lidatong/dataclasses-json/pull/196

**Comment by lidatong** [comment]
Hi, please take a look at [this section in the docs](https://github.com/lidatong/dataclasses-json#extending) on how to add `date` functionality

**Comment by lidatong** [comment]
@MichaelAzimov responded to you [here](https://github.com/lidatong/dataclasses-json/issues/139#issuecomment-640077089)
