### ISSUE TITLE
dataclassjson can't searlize float attribute

### ISSUE THREAD

**Issue by laskdjlaskdj12** [lidatong/dataclasses-json#218]
dataclass_json can't convert to float variable.
example code is under below

Example Code

Data class
```
@dataclass_json
@dataclass
class GpsLocationDTO:
    latitude: float
    longitude: float
    height: float
    vertical_accuracy: float
    horizontal_accuracy: float
``` 

Desealize Action Code
```
    request_str = request.data.decode("UTF_8")
    dict_request_data_json = ast.literal_eval(request_str)
    gpsLocationDTO = GpsLocationDTO.from_dict(dict_request_data_json)
```

Wanted
print(str(type(longitude))) = <type float>

Actural
print(str(type(longitude))) = <type str>

**Comment by RunOrVeith** [comment]
You should at least provide the request_str to make this reproducible, otherwise one can just guess what is happening.
