### ISSUE TITLE
Union type fails to be deserialized from dict

### ISSUE THREAD

**Issue by kevinmu** [lidatong/dataclasses-json#222]
I seem to be facing a similar issue to https://github.com/lidatong/dataclasses-json/issues/82

Consider the following example:

```
from typing import Union

from dataclasses import dataclass
from dataclasses_json import dataclass_json


@dataclass_json
@dataclass
class SimpleExample:
    @dataclass_json
    @dataclass
    class A:
        f1: int

    @dataclass_json
    @dataclass
    class B:
        f2: str
    a_or_b: Union[A, B]

v: SimpleExample = SimpleExample.from_dict({'a_or_b': {'f1': 1}})
if isinstance(v.a_or_b, SimpleExample.A):
    print(v.a_or_b.f1)
elif isinstance(v.a_or_b, SimpleExample.B):
    print(v.a_or_b.f2)
else:
    print(v.a_or_b.__class__)
```

When I run this, it prints `<class 'dict'>`. So the library is failing to resolve the inner dictionary to one of the Union types. I'm using the latest version (0.4.3) of dataclasses-json. I saw that @FaraSeer posted a hack for the `from_json` case, not sure if there is a similar hack for the `from_dict` case. Really appreciate your help!

**Comment by kevinmu** [comment]
The same appears to be true for subclasses of a shared superclass, e.g.;

```
from dataclasses import dataclass
from dataclasses_json import dataclass_json

@dataclass_json
@dataclass
class Inter:
    pass

@dataclass_json
@dataclass
class A(Inter):
    f1: int

@dataclass_json
@dataclass
class B(Inter):
    f2: str

@dataclass_json
@dataclass
class SimpleExample:
    example_field: Inter


v1: SimpleExample = SimpleExample.from_dict({'example_field': {'f1': 1}})
v2 = SimpleExample(example_field=A(1))
v2dict = v2.to_dict()
v3 = SimpleExample.from_dict(v2dict)

print(v1.example_field.__class__)
print(v2.example_field.__class__)
print(v3.example_field.__class__)
```

This prints

**Comment by kevinmu** [comment]
Ok, it seems that @FaraSeer 's fix explicitly excluded `from_dict` and `from_json`. 

I was able to get a quick fix to the issue by modifying this section of the code in `_decode_generic` as follows: basically the idea is to look for an implementing `dataclass` that has the same fields as the dict being decoded. If we find one, then we decode the dict to that class, else we leave it as is.

```        
    else:  # Union (already decoded or unsupported 'from_json' used)
            if isinstance(value, dict):
                impl_type_found = False
                for impl_type in type_.__args__:
                    if is_dataclass(impl_type):
                        if impl_type.__dataclass_fields__.keys() == \
                                value.keys():
                            res = _decode_dataclass(impl_type, value, infer_missing)
                            impl_type_found = True
                            break
                if not impl_type_found:
                    res = value
            else:
                res = value
```

Is this functionality something that you think would be valuable to have in the library? It makes a lot of sense for my use-case to be able to auto-resolve these union types.

**Comment by RunOrVeith** [comment]
If you want to do that, you need to consider the following edge cases:

- What if multiple dataclasses match the signature (I'd suggest to raise an error)
- The way you are currently doing it, you are ignoring default arguments. You'd have to check that value.keys() is a subset of impl_type.__dataclass_fields__.keys(), and that all the missing fields have a default (including default_factory). 
- Also I am not sure if fields marked with `init=False` are included in `impl_type.__dataclass_fields__.keys()` or not, that should be checked

**Comment by kevinmu** [comment]
Hm ok, I did a bit more reading into the concept of polymorphic deserialization, and I can see why `from_json` and `from_dict` were excluded last time. Like @RunOrVeith mentioned there are several edge cases with the above approach, plus it doesn't handle more complicated cases like, for instance, `Union[A, B, List[Union[A, C, D]]]`. I do think it's possible to handle these complex types with a recursive solution, but it might make the deserialization slower. So I'm less sure whether it's the right thing to do, although open to input from others!

For now I figured out a way to utilize the `marshmallow` deserialization, which is unambiguous through its examination of the `__type` attribute; just had to finangle with my JSON inputs.

**Comment by lidatong** [comment]
Hi, thanks for raising this issue and providing an example. @RunOrVeith raises good points, specifically the first on matching multiple signatures.

Typically, when faced with issues like this I take a look at how other codec libraries handle this same problem. The `jackson` library in Java, Scala's `circe`, even `protobuf`.

Consider this slight modification of your code: what would happen in your code if you have two classes with the same field name?

@dataclass_json
@dataclass
class A(Inter):
    f1: int

@dataclass_json
@dataclass
class B(Inter):
    f1: int

@RunOrVeith suggested raising an error. Personally, I would favor de-serializing into the first type that works, and documenting this, and perhaps making it configurable whether it's an error or not.

**Comment by lidatong** [comment]
A more theoretical way to look at it, is object -> json is no longer a one-to-one function mapping. More than one potential output json maps back to the same input. Another solution avenue would be to attach metadata to the json output -- but this now couples the user's json output to the library (not a good approach in my view)

**Comment by jacobg** [comment]
cattrs's approach to disambiguation seems to work:
https://cattrs.readthedocs.io/en/latest/structuring.html?highlight=Disambiguation#manual-disambiguation

Here's a unit test for dataclasses-json for a Union of a class and its subclass:
```python
import dataclasses
import typing

from dataclasses_json import dataclass_json


@dataclass_json()
@dataclasses.dataclass(frozen=True)
class A:
    foo: int


@dataclass_json()
@dataclasses.dataclass(frozen=True)
class B(A):
    bar: int


@dataclass_json()
@dataclasses.dataclass(frozen=True)
class C:
    a: typing.Union[A, B]


def _assert_using_schema(o):
    assert o == o.__class__.schema().load(o.__class__.schema().dump(o))

def test_disambiguate_superclass_using_schema():
    c = C(a=A(foo=1))
    _assert_using_schema(c)


def test_disambiguate_subclass_using_schema():
    c = C(a=B(foo=1, bar=2))
    _assert_using_schema(c)
```

The first unit test passes, but the second one fails.

The analogous version using cattrs works in both cases:
```python
import typing

import attr
import cattr


@attr.s(frozen=True, slots=True)
class A:
    foo: int = attr.ib()


@attr.s(frozen=True, slots=True)
class B(A):
    bar: int = attr.ib()


@attr.s(frozen=True, slots=True)
class C:
    a: typing.Union[A, B] = attr.ib()


def _assert_using_structure(o):
    assert o == cattr.structure(cattr.unstructure(o), o.__class__)


def test_disambiguate_superclass_using_structure():
    c = C(a=A(foo=1))
    _assert_using_structure(c)


def test_disambiguate_subclass_using_structure():
    c = C(a=B(foo=1, bar=2))
    _assert_using_structure(c)
```

**Comment by george-zubrienko** [comment]
Really old version used in the example - reopen if the latest still has this issue

**Comment by idbentley** [comment]
This is still an error with 0.5.14

```
import dataclasses
from dataclasses_json import dataclass_json
from typing import Union
from dataclasses_json import DataClassJsonMixin
from dataclasses import make_dataclass

@dataclass_json
@dataclasses.dataclass
class First:
    first_field: str = dataclasses.field()

class Second:
    second_field: str = dataclasses.field()

@dataclass_json
@dataclasses.dataclass
class TestClass:
    foo: Union[First,Second] = dataclasses.field()

if __name__ == "__main__":
    unmarshal = make_dataclass("Unmarchal", [("foo", TestClass)], bases=(DataClassJsonMixin, ))
    json_dict = {'foo': {'foo': {'first_field': 'bar'}}}
    out = unmarshal.from_dict(json_dict)
    # print(out.foo.foo)
    assert(not isinstance(out.foo.foo, dict))
```
```
Traceback (most recent call last):
  File ".../test/test.py", line 25, in <module>
    assert(not isinstance(out.foo.foo, dict))
AssertionError

```

**Comment by idbentley** [comment]
@george-zubrienko sorry, I meant to tag you in the previous comment.

**Comment by PatrickF1** [comment]
> Ok, it seems that @FaraSeer 's fix explicitly excluded from_dict and from_json.

Why does the fix explicitly exclude from_dict and from_json? And could you link to the fix please? Thanks!

**Comment by idbentley** [comment]
Hi @PatrickF1, there have been a few PRs recently that fixed this behaviour: https://github.com/lidatong/dataclasses-json/pull/475, https://github.com/lidatong/dataclasses-json/pull/478

I can no longer repro this issue with `0.6.1`

**Comment by PatrickF1** [comment]
Hi @idbentley , thanks for the reply.

I actually deleted my original comment because I found out the answer. But for posterity here it is:
> Ok, it seems that @FaraSeer 's fix explicitly excluded from_dict and from_json.
Can you explain why the fix explicitly excluded from_dict and from_json? And can you link to the commit?
