### ISSUE TITLE
Provide dump and load methods

### ISSUE THREAD

**Issue by Spenhouet** [lidatong/dataclasses-json#226]
I wish the dataclass would have integrated dump and load methods to save the data to a JSON file or to load it from a JSON file.

This should be relatively easy to add, if this is a welcome feature I could create a pull request.

This would dump / save the dataclass to a JSON file:

    my_dataclass.dump(file_path)

This would load and serialize JSON from a file to a dataclass:

    my_dataclass = MyDataclass.load(file_path)

Going by the `to_json` and `from_json` implementation this should be something like this:

    def dump(self,
             file_path: Union[str, Path],
             *,
             skipkeys: bool = False,
             ensure_ascii: bool = True,
             check_circular: bool = True,
             allow_nan: bool = True,
             indent: Optional[Union[int, str]] = None,
             separators: Tuple[str, str] = None,
             default: Callable = None,
             sort_keys: bool = False,
             **kw) -> None:
        path = Path(file_path)
        with path.open("w") as json_file:
            json.dump(self.to_dict(encode_json=False),
                              json_file,
                              cls=_ExtendedEncoder,
                              skipkeys=skipkeys,
                              ensure_ascii=ensure_ascii,
                              check_circular=check_circular,
                              allow_nan=allow_nan,
                              indent=indent,
                              separators=separators,
                              default=default,
                              sort_keys=sort_keys,
                              **kw)

    @classmethod
    def load(cls: Type[A],
             file_path: Union[str, Path],
             *,
             parse_float=None,
             parse_int=None,
             parse_constant=None,
             infer_missing=False,
             **kw) -> A:
        path = Path(file_path)
        with path.open("r") as json_file:
            kvs = json.load(json_file,
                             parse_float=parse_float,
                             parse_int=parse_int,
                             parse_constant=parse_constant,
                             **kw)
        return cls.from_dict(kvs, infer_missing=infer_missing)

**Comment by lidatong** [comment]
Hi, I had considered adding similar methods in the past -- at the time, I decided to keep the API as concise as possible, but will reconsider this.

As a side note, I would change your example to not necessarily assuming a file path, instead taking in a `file-like` object with a `.write()` method ("protocol") -- consider a Unix socket for example

**Comment by Spenhouet** [comment]
Makes sense. Thanks for reconsidering.

For the meantime if anyone comes across this feature request, you could inherit your dataclass from this one:

```
from __future__ import annotations

import json
from pathlib import Path
from typing import Union, Type, TypeVar

from dataclasses_json import DataClassJsonMixin

T = TypeVar('T', bound="JsonDataClass")


class JsonDataClass(DataClassJsonMixin):
    """Wrapper to extend the functionality of DataClassJsonMixin."""

    def save(self, file_path: Union[str, Path]) -> None:
        """
        Save the dataclass as JSON file.

        Args:
            file_path (Union[str, Path]): The JSON file path.
        """
        path = Path(file_path)
        with path.open("w") as json_file:
            json.dump(self.to_dict(encode_json=False), json_file, indent=2)

    @classmethod
    def load(cls: Type[T], file_path: Union[str, Path]) -> T:
        """
        Load a JSON file and serialize it to an instance of dataclass T.

        Args:
            cls (Type[T]): The dataclass type.
            file_path (Union[str, Path]): The JSON file path.

        Returns:
            T: The initialized instance of dataclass T.
        """
        path = Path(file_path)
        with path.open("r") as json_file:
            json_res = json.load(json_file)
        return cls.from_dict(json_res)
```

This can then be used like this:
```
@dataclass
class SimpleExample(JsonDataClass):
    example: str = ""
```


> I would change your example to not necessarily assume a file path, instead taking in a file-like object with a .write() method ("protocol") -- consider a Unix socket for example

Thanks for the recommendation but I did not get what type of parameter you would expect. Could you add an example?

**Comment by lidatong** [comment]
> Thanks for the recommendation but I did not get what type of parameter you would expect. Could you add an example?

Sure, sorry for not being clear. This example from the official `json` module is a good one: https://docs.python.org/3/library/json.html#json.dump (see the description after the signature)

**Comment by Spenhouet** [comment]
Thanks. Now I get what you where referring to. I thought you meant that in general there is a better way but you were specifically referring to the integration into this package.
I agree with that. Everyone using these methods would expect them to behave equally to the json package counterparts. Saving it to a file this way is our use case and good for us but not for this package.
