### ISSUE TITLE
deserialization doesn't check types on deserialization

### ISSUE THREAD

**Issue by bmc-msft** [lidatong/dataclasses-json#230]
Example:

```
@dataclass_json
@dataclass
class A:
    b: int

A.from_dict({"b": "a"})
A.from_json('{"b": "a"}')
```

I would expect either from_dict or from_json to generate exceptions, or some other way to validate without writing a custom __post_init__ to check each field.

In order to use dataclass in an API boundary, such as a RESTful API, data validation is important.

**Comment by RunOrVeith** [comment]
Please see `A.schema().loads`

**Comment by matt035343** [comment]
Same as #260
