### ISSUE TITLE
Recursive LetterCase and dict/list attributes

### ISSUE THREAD

**Issue by tduboys** [lidatong/dataclasses-json#242]
Hi,

I'm using dataclasses-json on a full snake_case project, but want to have a representation on CamelCase
I'm using the `@dataclasses_json(letter_caseLetterCase.Camel)` decorator and it works as I want, but is not recursive on dict/list attributes.

Is there a way to replace key names on dict attributes ?

As an example : 
```
@dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
class Example:
    example_id: int
    example_datas: dict
example_item = Example(1, {"data_id": 1})
example_item.to_dict()
-> {'exampleId': 1, 'exampleDatas': {'data_id': 1}}
```

And the expected result is : 
``` 
example_item.to_dict()
-> {'exampleId': 1, 'exampleDatas': {'dataId': 1}}
```

If someone have an idea to do that…

Many thanks

**Comment by matt035343** [comment]
There is currently no way of doing this in `dataclasses-json`, and I am not sure it should be part of this library as I believe it should only do actions on the defined schemas.

I am open to hear other opinions on this.

**Comment by matt035343** [comment]
Closing for above reason and due to staleness
