### ISSUE TITLE
How to pass undefined=Undefined.EXCLUDE via mixin?

### ISSUE THREAD

**Issue by TonalidadeHidrica** [lidatong/dataclasses-json#247]
I can use `@dataclasses(undefined=Undefined.EXCLUDE)` as an annotation to a class definition to specify the behavior for undefined fields.  How can I specify it when I used Mixin instead of annotation?

**Comment by nrhoffmann** [comment]
I came across this somewhere.

```
@dataclass
class ApiRequest(DataClassJsonMixin):
    dataclass_json_config = config(
        letter_case=LetterCase.CAMEL,
        undefined=Undefined.EXCLUDE
    )['dataclasses_json']
```

See https://github.com/lidatong/dataclasses-json/issues/194.

**Comment by hiboo** [comment]
I was looking for this, thank you! I think this should end up in the documentation as well.
