### ISSUE TITLE
Change case (de)serialization when using DataClassJsonMixin ?

### ISSUE THREAD

**Issue by eLvErDe** [lidatong/dataclasses-json#272]
Hello,

I tried to switch from decorator to mixin because Mypy struggles to understand what methods are available but I cannot figure out how to set case handling.
I tried the following:

```python
class DataClassJsonMixinCamelCase(dataclasses_json.DataClassJsonMixin):
    """
    Inherit from DataClassJsonMixin and configure camelCase serialization/deserialization
    """

    dataclass_json_config = dataclasses_json.cfg.config(letter_case=dataclasses_json.LetterCase.CAMEL)
```

I also tried to overwrite dataclasses_json.config from file scope with no luck.

How can I do that ?

Thanks.

**Comment by AbdulRahmanAlHamali** [comment]
Hi @eLvErDe , can you try this:
```
dataclass_json_config = dataclasses_json.cfg.config(letter_case=dataclasses_json.LetterCase.CAMEL)['dataclasses_json']
```
I'm not sure if it'll work, but I stole it from here:
https://github.com/lidatong/dataclasses-json/blob/master/dataclasses_json/api.py#L140

**Comment by gubser** [comment]
@AbdulRahmanAlHamali thank you for the hint. I put it into a new class for easier reuse:

```python
from dataclasses_json import DataClassJsonMixin
import dataclasses_json

class DataClassJsonCamelMixIn(DataClassJsonMixin):
    dataclass_json_config = dataclasses_json.config( # type: ignore
        letter_case=dataclasses_json.LetterCase.CAMEL, # type: ignore
        undefined=dataclasses_json.Undefined.EXCLUDE
    )['dataclasses_json']
```

**Comment by jmhodges-color** [comment]
Would love to hear of an API for this!  We're using the mixin for the type checking (which is great!) and this particular construction feels a lil funny to add.

**Comment by george-zubrienko** [comment]
#442 v1 API should make things easier here
