### ISSUE TITLE
Supporting PEP 585

### ISSUE THREAD

**Issue by odashi** [lidatong/dataclasses-json#273]
I am reporting this issue because I met several problems when migrating our code with `dataclasses-json` to a newer version of Python.

As of [PEP 585](https://www.python.org/dev/peps/pep-0585/), effective from Python 3.9, type generics defined in `typing` is deprecated, and subscribing standard types (like `list[str]`) will become only the way to annotate these kinds of types in the future. It is somewhat encouraged to support this feature by `dataclasses-json` too.

**Comment by george-zubrienko** [comment]
Issue lacks examples - feel free to reopen with some code we can look at :)
