### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by pauldraper** [lidatong/dataclasses-json#293]
Is this project alive?

Last commit was June 2020, and issues and PRs since then seem to have no contributor activity.

**Comment by lidatong** [comment]
Yes it's still alive. I'm sorry I haven't been very active. It's been a busy year for me. I'm going to set aside some time this weekend to go through outstanding issues and PRs.

For those following: I'm sorry I haven't dedicated more time to this. I genuinely appreciate the contributions from everyone reporting issues / making PRs along the way.
