### ISSUE TITLE
TypeError: Type Dict cannot be instantiated; use dict() instead

### ISSUE THREAD

**Issue by George3d6** [lidatong/dataclasses-json#302]
I'm getting this error, is the package not able to work with the new generic python Typing?

**Comment by tindzk** [comment]
I encountered a similar exception with lists which might be the same underlying bug: https://github.com/lidatong/dataclasses-json/issues/310

**Comment by amjed-ali-k** [comment]
[https://stackoverflow.com/questions/58558412/typeerror-type-tuple-cannot-be-instantiated-use-tuple-instead](url)

**Comment by JonathanRoach** [comment]
Have just encountered this in my code. It's probably these lines in core.py (around line 267) masking an issue with something inside your dict:
        try:
            res = _get_type_cons(type_)(xs)
        except (TypeError, AttributeError):
            res = type_(xs)
As a work-around I replaced them with these:
        try:
            tp = _get_type_cons(type_)
        except (TypeError, AttributeError):
            tp = type_
        res = tp(xs)
which exposed the issue in my dataclass inside my dict.

**Comment by matt035343** [comment]
Closing due to lack of details.
Maybe related to https://github.com/lidatong/dataclasses-json/issues/232.
Please reopen if the issue persists or if you can provide more details.
