### ISSUE TITLE
Add a `many` option to `DataClassJsonMixin.from_json`

### ISSUE THREAD

**Issue by Peilonrayz** [lidatong/dataclasses-json#32]
Currently the only way to get a `List[T]` with your code is with the example:

>     Person.schema().loads(people_json,` many=True)

I however can't get this to work with `infer_missing` when my REST endpoints elect to remove the key on optional return values. Since this would change the return type of `from_json` from `A` to `Union[A, List[A]]`, you may want to make a function `from_jsons` instead.

**Comment by lidatong** [comment]
Hi, thanks for raising this use case!

This is addressed in two ways in the [latest release](https://github.com/lidatong/dataclasses-json/releases/tag/v0.0.25):

1. `.schema` will now generate defaults. If your dataclass field uses `default` or `default_factory`, `@dataclass_json` will now supply a corresponding field default to the generated marshmallow schema (so if the key is missing in the JSON, the default will be filled for that key).
2. `.schema` has an `infer_missing` parameter. If your dataclass field is `Optional` without a default,  calling `.schema(infer_missing=True)` will fill `None` when the key is missing.

I think the 2nd should cover your use case, but you can also solve it by attaching a default to your dataclass e.g.

```python
class Example:
    x: int = 0
```
