### ISSUE TITLE
Missing intersphinx mapping file

### ISSUE THREAD

**Issue by PhilippSelenium** [lidatong/dataclasses-json#324]
When including dataclasses_json in my project I cannot create an interpshinx mapping using the objects.inv file
I have to exclude certain members of dataclasses_json in order to get the sphinx build running:

```
    :no-show-inheritance:
    :exclude-members: __eq__, __init__, __repr__, to_dict, to_json, schema, from_dict, from_json
```

**Comment by george-zubrienko** [comment]
Sorry not familiar with sphinx - but if you submit a PR, will happily integrate :)
