### ISSUE TITLE
testsuite failure on tests/test_annotations.py::TestAnnotations::test_type_hints

### ISSUE THREAD

**Issue by baldurmen** [lidatong/dataclasses-json#335]
Hi,
Using the latest release (0.5.6), I'm getting this error when I run the testsuite:
```
=== python3.10 ===
============================= test session starts ==============================
platform linux -- Python 3.10.1, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
rootdir: /tmp/autopkgtest-lxc.mmk2a2lv/downtmp/autopkgtest_tmp
plugins: hypothesis-5.43.3
collected 234 items

tests/test_annotations.py
=== python3.9 ===
============================= test session starts ==============================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
rootdir: /tmp/autopkgtest-lxc.mmk2a2lv/downtmp/autopkgtest_tmp
plugins: hypothesis-5.43.3
collected 234 items

tests/test_annotations.py
autopkgtest [06:31:41]: test unittests: -----------------------]
```
I can't get anything more detailed than that, even running the test verbosely (it just exits with error code 1). Skipping `tests/test_annotations.py::TestAnnotations::test_type_hints` solves the issue.

Looking at your CI, it seems you're hitting the same bug, but I couldn't find an issue here tracking it.

Cheers,

**Comment by USSX-Hares** [comment]
Found the root cause.
MyPy added a parameter `clean_exit` which must be set to `True` in order to intercept `SystemExit`.
