### ISSUE TITLE
Error did not occur when specifying incorrect type hint

### ISSUE THREAD

**Issue by yuji38kwmt** [lidatong/dataclasses-json#366]
# Environmental
* Python3.10.2
* dataclasses-json 0.5.7

# What's happened?
I mistook type hint of `type` , but error did not occur. 
Why did error occurred?

I hope that error will occur when specifying incorrect type hint.

```
from dataclasses import dataclass
from dataclasses_json import dataclass_json


@dataclass_json
@dataclass
class Person:
    name: str
    type: dict[str, str]
    """incorrect type hint"""


@dataclass_json
@dataclass
class School:
    name: str
    people: list[Person]
    """type

d_person = {"name": "Alice", "type": "junior"}
d_school = {"name": "tokyo", "people": [d_person]}

school = School.from_dict(d_school)
print(school)
````

```
$ python bar.py
School(name='tokyo', people=[])
```

**Comment by andersk** [comment]
The documentation says that [validation does not occur by default](https://lidatong.github.io/dataclasses-json/#quickstart). To get validation, you need to do `school = School.schema().loads(d_school)` instead.

**Comment by yuji38kwmt** [comment]
Thanks !
