### ISSUE TITLE
Leading underscore are not kept in `to_dict` method

### ISSUE THREAD

**Issue by clementta** [lidatong/dataclasses-json#376]
Hi,

Here is an example:
Having this sample:
```py
from typing import Optional
from dataclasses_json import LetterCase, Undefined, config, dataclass_json
from dataclasses import dataclass, field

@dataclass_json(undefined=Undefined.EXCLUDE, letter_case=LetterCase.CAMEL)
@dataclass
class Document:
    field_1: str
    field_2: Optional[str] = None
    _field_3: Optional[str] = None
    _field_4: Optional[int] = None
```

In version 0.5.4:
```py
Document(field_1="hello").to_dict()
#  {'field_1': 'hello', 'field_2': None, '_field_3': None, '_field_4': None}
```

In version 0.5.5 and above:
```py
Document(field_1="hello").to_dict()
#  {'field_1': 'hello', 'field_2': None, 'field_3': None, 'field_4': None}
```

I am expecting 0.5.4 and lower behavior.

* Is this a wanted feature ?
* Is there an config option to go back to the leading _ in dict ?

Thank you

**Comment by matt035343** [comment]
I recreated this, and to me this is not a bug, because you are using camelCase. Underscores are not used in camelCase, and your example actually highlights a bug in the camelCase serialization; the number in the end should be spearated with an underscore.

I have opened a PR to fix this. Thanks!
