### ISSUE TITLE
errors to do with type mismatches just swallowed by library

### ISSUE THREAD

**Issue by TristanSpeakEasy** [lidatong/dataclasses-json#392]
For example if the json contains an array field but the dataclass is expecting a dict[str, str] the resulting error is swallowed and the library will return an empty object instead of printing any useful error

**Comment by george-zubrienko** [comment]
@TristanSpeakEasy one more ping, I'll close the issue - but you are welcome to re-open it or create a new one using our new fancy template ;)

**Comment by TristanSpeakEasy** [comment]
thanks @george-zubrienko sorry for the delay I got round to getting a reproducible together here https://github.com/lidatong/dataclasses-json/issues/422
