### ISSUE TITLE
Running tests/code locally with Python 3.7 requires installing importlib-metadata 4.*

### ISSUE THREAD

**Issue by deansg** [lidatong/dataclasses-json#396]
When fresh cloning the repository, installing from pipfile (new venv) and trying to run any tests/code using the library with Python 3.7, exceptions are thrown in case importlib-metadata isn't already installed (and in a version that is compatible with 4).

I'm not sure what is the right way to solve this, but for local development I needed to add this to the pipfile.

**Comment by george-zubrienko** [comment]
Should be resolved by switching to Poetry #413
