### ISSUE TITLE
Update test_annotations.py to be compatible with mypy >= 0.991

### ISSUE THREAD

**Issue by Maniatty** [lidatong/dataclasses-json#401]
Newer versions of `mypy` fail in test  (the results shown are based on  `mypy  0.991`, which was installed in a fresh virtual environment via `pip install .[dev]`.
Apparently test_annotations.py  invokes  `mypy.main.main` that now uses named parameters instead of positional parameters,
and no longer takes the path parameter.  The test `test_annotations. test_type_hints` uses the now stale api which does not work:
 `pytest test_annotations.py` :

```python
    def test_type_hints(self):
        text_io = StringIO('')
        try:
            # mypy.main uses sys.stdout for printing
            # We override it to catch error messages
>           mypy_main(None, text_io, text_io, [__file__], clean_exit=True)
E           TypeError: main() takes at most 4 arguments (5 given)
```
Replacing the now obsolete call to main with the following allows the test to pass.
```python
            mypy_main(stdout=text_io, stderr=text_io, args= [__file__], clean_exit=True)
```

**Comment by george-zubrienko** [comment]
Issue is more than half a year old - I'm closing this as stale (might need to add a bot to do this later)
