### ISSUE TITLE
[BUG] dataclasses-json not throwing error on mismatched types between array and object

### ISSUE THREAD

**Issue by TristanSpeakEasy** [lidatong/dataclasses-json#422]
### Description

So I have a small reproducible that I would have expected to throw an exception as the data type defined in the dataclass is different to that supplied in the JSON but instead of throwing an exception and failing, the code continues and just returns an empty value.

In the below example the JSON contains an array of strings, but the dataclass is expecting an optional dictionary `Optional[dict[str, Any]]`

The below snippet just prints: `Results(results=[])` instead of the exception I would have expected

### Code snippet that reproduces the issue

```python
import json
import traceback
from dataclasses import dataclass, make_dataclass
from typing import Any, Optional

from dataclasses_json import DataClassJsonMixin, dataclass_json


@dataclass_json
@dataclass
class Person:
    metadata: Optional[dict[str, Any]]


@dataclass_json
@dataclass
class Result:
    record: Person


@dataclass_json
@dataclass
class Results:
    results: list[Result]


try:
    results = Results.from_json(
        '{"results": [{"record": {"metadata": ["hi"]}}]}')
    print(results)
except Exception as e:
    print("error")
    print(repr(e))
    traceback.print_exc()
```

### Describe the results you expected

I would expect the above example to throw an exception to do with mismatched types

### Python version you are using

3.9

### Environment description

dataclasses-json==0.5.8
marshmallow==3.19.0
marshmallow-enum==1.5.1
mypy-extensions==1.0.0
packaging==23.1
typing-inspect==0.9.0
typing_extensions==4.6.3

**Comment by george-zubrienko** [comment]
Definitely an issue, will try to take a look this week and draft a fix, thanks for reporting!

**Comment by george-zubrienko** [comment]
Bit delayed here, this one is next on my todo after we merge Poetry PR - sorry :)

**Comment by george-zubrienko** [comment]
@TristanSpeakEasy I feel really bad about this lol... But I've tested your example with 0.5.12 release on py3.11 env and this is what I got:

Faulty one as in your code snippet:

```
try:
    results = Results.from_json(
        '{"results": [{"record": {"metadata": ["hi"]}}]}')
    print(results)
except Exception as e:
    print("error")
    print(repr(e))
    traceback.print_exc()
    
error
AttributeError("'list' object has no attribute 'keys'")
Traceback (most recent call last):
  ...
```

Correct one:
```
try:
    results = Results.from_json(
        '{"results": [{"record": {"metadata": {"key": 123}}}]}')
    print(results)
except Exception as e:
    print("error")
    print(repr(e))
    traceback.print_exc()

Results(results=[Result(record=Person(metadata={'key': 123}))])
```

Can you retest as well and let me know if somebody magically fixed this in the past month? :)

**Comment by george-zubrienko** [comment]
Or, if you think the error is misleading, let me know what you think should be printed instead

**Comment by TristanSpeakEasy** [comment]
Hey @george-zubrienko this does seem to be resolved in the latest version of the package, I now see an AttributeError where I wasn't before
