### ISSUE TITLE
[BUG] Release 0.5.9 missing from pypi

### ISSUE THREAD

**Issue by jayofdoom** [lidatong/dataclasses-json#428]
### Description

Hello,

I was trying to troubleshoot a type hinting issue using this library, and I saw according to github I was not running the latest release -- https://github.com/lidatong/dataclasses-json/releases/tag/v0.5.9. It looks like the CI job failed: https://github.com/lidatong/dataclasses-json/actions/runs/5268334225.

Good luck getting it fixed! I'll update my pyproject.toml to pull from github in the meantime.

### Code snippet that reproduces the issue

pip install dataclasses-json==0.5.9

### Describe the results you expected

Shiny new dataclasses-json

### Python version you are using

3.11.4

### Environment description

> pip install dataclasses-json==0.5.9
ERROR: Could not find a version that satisfies the requirement dataclasses-json==0.5.9 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8)
ERROR: No matching distribution found for dataclasses-json==0.5.9

also https://pypi.org/project/dataclasses-json/#history

**Comment by george-zubrienko** [comment]
Thanks for reporting this! Will fix next week

**Comment by george-zubrienko** [comment]
0.5.9 pending approval https://github.com/lidatong/dataclasses-json/actions/runs/5426510917

**Comment by george-zubrienko** [comment]
@jayofdoom 0.5.9 is now on PyPI - sorry for the delay :)

https://pypi.org/project/dataclasses-json/0.5.9/

**Comment by jayofdoom** [comment]
Hey, no big deal :) Thanks for the quick fix and the useful library.
