### ISSUE TITLE
[BUG] NameError when using dataclass_json with pulumi.Input

### ISSUE THREAD

**Issue by yoanisgil** [lidatong/dataclasses-json#429]
### Description

Hi there,

I've been using the project for a while for decoding configuration from Pulumi projects as dataclasses. Thus far it has been very helpful and working out of the box. However, I have this class:

```python
@dataclass_json
@dataclasses.dataclass
class LambdaDeploymentConfig:
    policy_arn: Union[pulumi.Input[str], str] = ""
    role_arn: Union[pulumi.Input[str], str] = ""
```

that when attempting to decode a JSON object, leads to this error:

```
E               Traceback (most recent call last):
E                 File "/Users/yoanis/Library/Caches/pypoetry/virtualenvs/pulumi-sliq-u01K2MV2-py3.11/lib/python3.11/site-packages/pulumi/automation/_server.py", line 81, in Run
E                   loop.run_until_complete(run_in_stack(self.program))
E                 File "/Users/yoanis/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
E                   return future.result()
E                          ^^^^^^^^^^^^^^^
E                 File "/Users/yoanis/Library/Caches/pypoetry/virtualenvs/pulumi-sliq-u01K2MV2-py3.11/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 136, in run_in_stack
E                   await run_pulumi_func(lambda: Stack(func))
E                 File "/Users/yoanis/Library/Caches/pypoetry/virtualenvs/pulumi-sliq-u01K2MV2-py3.11/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
E                   func()
E                 File "/Users/yoanis/Library/Caches/pypoetry/virtualenvs/pulumi-sliq-u01K2MV2-py3.11/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 136, in <lambda>
E                   await run_pulumi_func(lambda: Stack(func))
E                                                 ^^^^^^^^^^^
E                 File "/Users/yoanis/Library/Caches/pypoetry/virtualenvs/pulumi-sliq-u01K2MV2-py3.11/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 159, in __init__
E                   func()
E                 File "/Users/yoanis/Documents/Projects/SportLogiq/cicdinfrastructurecore/pulumi-sliq/tests/patterns/test_lambda.py", line 72, in pulumi_program
E                   execute()
E                 File "/Users/yoanis/Documents/Projects/SportLogiq/cicdinfrastructurecore/pulumi-sliq/pulumi_sliq/patterns/lambda_.py", line 24, in execute
E                   deployment_config: LambdaDeploymentConfig = LambdaDeploymentConfig.from_dict(data)  # type: ignore
E                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E                 File "/Users/yoanis/Library/Caches/pypoetry/virtualenvs/pulumi-sliq-u01K2MV2-py3.11/lib/python3.11/site-packages/dataclasses_json/api.py", line 70, in from_dict
E                   return _decode_dataclass(cls, kvs, infer_missing)
E                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E                 File "/Users/yoanis/Library/Caches/pypoetry/virtualenvs/pulumi-sliq-u01K2MV2-py3.11/lib/python3.11/site-packages/dataclasses_json/core.py", line 161, in _decode_dataclass
E                   types = get_type_hints(cls)
E                           ^^^^^^^^^^^^^^^^^^^
E                 File "/Users/yoanis/.pyenv/versions/3.11.1/lib/python3.11/typing.py", line 2302, in get_type_hints
E                   value = _eval_type(value, base_globals, base_locals)
E                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E                 File "/Users/yoanis/.pyenv/versions/3.11.1/lib/python3.11/typing.py", line 370, in _eval_type
E                   ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
E                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E                 File "/Users/yoanis/.pyenv/versions/3.11.1/lib/python3.11/typing.py", line 370, in <genexpr>
E                   ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
E                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E                 File "/Users/yoanis/.pyenv/versions/3.11.1/lib/python3.11/typing.py", line 359, in _eval_type
E                   return t._evaluate(globalns, localns, recursive_guard)
E                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E                 File "/Users/yoanis/.pyenv/versions/3.11.1/lib/python3.11/typing.py", line 854, in _evaluate
E                   eval(self.__forward_code__, globalns, localns),
E                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E                 File "<string>", line 1, in <module>
E               NameError: name 'T' is not defined
```

strange enough, if I add this to the top of the file where the class `LambdaDeploymentConfig` is defined, everything works as expected.

I just thought of reporting this in case it might be useful to someone else.

### Code snippet that reproduces the issue

```python
import pulumi
from typing import Union

@dataclass_json
@dataclasses.dataclass
class LambdaDeploymentConfig:
    policy_arn: Union[pulumi.Input[str], str] = ""
    role_arn: Union[pulumi.Input[str], str] = ""
```

### Describe the results you expected

I would expect the code not to produce the exception mentioned above.

### Python version you are using

3.11

### Environment description

Arpeggio==2.0.0
attrs==23.1.0
aws-sam-translator==1.69.0
aws-xray-sdk==2.12.0
blinker==1.6.2
boto3==1.26.156
boto3-stubs==1.26.156
botocore==1.29.156
botocore-stubs==1.29.156
certifi==2023.5.7
cffi==1.15.1
cfn-lint==0.77.9
charset-normalizer==3.1.0
click==8.1.3
coverage==7.2.7
cryptography==41.0.1
dataclasses-json==0.5.8
dill==0.3.6
docker==6.1.3
ecdsa==0.18.0
Flask==2.3.2
Flask-Cors==3.0.10
graphql-core==3.2.3
grpcio==1.51.3
idna==3.4
iniconfig==2.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
jschema-to-python==1.2.3
jsondiff==2.0.0
jsonpatch==1.33
jsonpickle==3.0.1
jsonpointer==2.4
jsonschema==4.17.3
jsonschema-spec==0.1.6
junit-xml==1.9
lazy-object-proxy==1.9.0
MarkupSafe==2.1.3
marshmallow==3.19.0
marshmallow-enum==1.5.1
moto==4.1.11
mpmath==1.3.0
mypy-boto3-cloudformation==1.26.156
mypy-boto3-dynamodb==1.26.152
mypy-boto3-ec2==1.26.156
mypy-boto3-iam==1.26.155
mypy-boto3-lambda==1.26.147
mypy-boto3-rds==1.26.144
mypy-boto3-s3==1.26.155
mypy-boto3-secretsmanager==1.26.135
mypy-boto3-sqs==1.26.148
mypy-extensions==1.0.0
networkx==3.1
openapi-schema-validator==0.4.4
openapi-spec-validator==0.5.7
packaging==23.1
parver==0.4
pathable==0.4.3
pbr==5.11.1
pluggy==1.0.0
protobuf==4.23.3
pulumi==3.72.2
pulumi-aws==5.41.0
pulumi-aws-tags==0.4.1
-e git+ssh://git@bitbucket.org/sportlogiqteam/cicdinfrastructurecore.git@6da7ff3924bb43297351e8e15a2a5346c332f48d#egg=pulumi_sliq&subdirectory=pulumi-sliq
py-partiql-parser==0.3.3
pyasn1==0.5.0
pycparser==2.21
pydantic==1.10.9
pyparsing==3.1.0
pyrsistent==0.19.3
pytest==7.3.2
pytest-cov==4.1.0
python-dateutil==2.8.2
python-jose==3.3.0
PyYAML==6.0
regex==2023.6.3
requests==2.31.0
responses==0.23.1
rfc3339-validator==0.1.4
rsa==4.9
s3transfer==0.6.1
sarif-om==1.0.4
semver==2.13.0
six==1.16.0
sshpubkeys==3.3.1
sympy==1.12
types-awscrt==0.16.19
types-PyYAML==6.0.12.10
types-s3transfer==0.6.1
typing-inspect==0.9.0
typing_extensions==4.6.3
urllib3==1.26.16
websocket-client==1.6.0
Werkzeug==2.3.6
wrapt==1.15.0
xmltodict==0.13.0

**Comment by george-zubrienko** [comment]
@yoanisgil do you also have this error when inheriting from the Mixin class instead of using the annotation?

**Comment by yoanisgil** [comment]
@george-zubrienko unfortunately I cannot reproduce this anymore as I have added other dependencies to my project :(. Will keep an eye out just in case in pops-up again.

**Comment by george-zubrienko** [comment]
To be fair, we should probably be more explicit on whether a type user defines supports ser-deser. Will think about it.

**Comment by s-vitaliy** [comment]
@yoanisgil, looks like I was able to reproduce this issue without `dataclasses-json` library. It seems to be an issue in the get_type_hints  funciton. I created an issue in the python typing repository:  https://github.com/python/typing/issues/1426

As a workaround, you can import `Output` and `T` names from the module where `Input` is defined:
```python
from pulumi import Output
from pulumi.output import T
```

**Comment by s-vitaliy** [comment]
>Solving this without changing current semantics may be difficult or nearly impossible.

>It is also documented.

>Note [get_type_hints()](https://docs.python.org/3/library/typing.html#typing.get_type_hints) does not work with imported [type aliases](https://docs.python.org/3/library/typing.html#type-aliases) that include forward references. Enabling postponed evaluation of annotations ([PEP 563](https://peps.python.org/pep-0563/)) may remove the need for most forward references.

>https://docs.python.org/3/library/typing.html#typing.get_type_hints

(from the issue referenced above)

So, the reason of this behavior is the semantics of the python type system. Unfortunately, I don't think we can do much about it.
