### ISSUE TITLE
[BUG] release v0.5.10 not published to PyPi

### ISSUE THREAD

**Issue by edwargix** [lidatong/dataclasses-json#438]
### Description

This might be a repeat of the issue that happened for v0.5.9: <https://github.com/lidatong/dataclasses-json/issues/428>

<https://pypi.org/project/dataclasses-json/#history>

### Code snippet that reproduces the issue

```sh
(.venv) [~/tmp/dcj]$ pip install dataclasses-json==0.5.10
ERROR: Could not find a version that satisfies the requirement dataclasses-json==0.5.10 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9)
ERROR: No matching distribution found for dataclasses-json==0.5.10

[notice] A new release of pip available: 22.3.1 -> 23.2
[notice] To update, run: pip install --upgrade pip
(.venv) [~/tmp/dcj]$ pip install dataclasses-json==0.5.9 
Collecting dataclasses-json==0.5.9
  Downloading dataclasses_json-0.5.9-py3-none-any.whl (26 kB)
Collecting marshmallow<4.0.0,>=3.3.0
  Downloading marshmallow-3.19.0-py3-none-any.whl (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.1/49.1 kB 6.7 MB/s eta 0:00:00
Collecting marshmallow-enum<2.0.0,>=1.5.1
  Downloading marshmallow_enum-1.5.1-py2.py3-none-any.whl (4.2 kB)
Collecting typing-inspect>=0.4.0
  Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Collecting packaging>=17.0
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting mypy-extensions>=0.3.0
  Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Installing collected packages: typing-extensions, packaging, mypy-extensions, typing-inspect, marshmallow, marshmallow-enum, dataclasses-json
Successfully installed dataclasses-json-0.5.9 marshmallow-3.19.0 marshmallow-enum-1.5.1 mypy-extensions-1.0.0 packaging-23.1 typing-extensions-4.7.1 typing-inspect-0.9.0

[notice] A new release of pip available: 22.3.1 -> 23.2
[notice] To update, run: pip install --upgrade pip
```

### Describe the results you expected

v0.5.10 is available on pypi for tools like pip

### Python version you are using

3.11.3

### Environment description

builtin venv module environment:
```sh
python -m venv ...
```

**Comment by edwargix** [comment]
it looks like the `release`  job was skipped for the commit, 0ddfc1f, at v0.5.10: <https://github.com/lidatong/dataclasses-json/actions/runs/5566955859>

**Comment by lidatong** [comment]
> it looks like the `release` job was skipped for the commit, [0ddfc1f](https://github.com/lidatong/dataclasses-json/commit/0ddfc1f95f294902965e91983bcc24714734f4c4), at v0.5.10: https://github.com/lidatong/dataclasses-json/actions/runs/5566955859

thanks for pinpointing the issue. we're working on automating CI better per #413 ... apologies for the churn and bear with us...

**Comment by edwargix** [comment]
> > it looks like the `release` job was skipped for the commit, [0ddfc1f](https://github.com/lidatong/dataclasses-json/commit/0ddfc1f95f294902965e91983bcc24714734f4c4), at v0.5.10: https://github.com/lidatong/dataclasses-json/actions/runs/5566955859
> 
> thanks for pinpointing the issue. we're working on automating CI better per #413 ... apologies for the churn and bear with us...

No worries!  Thanks a lot!

**Comment by george-zubrienko** [comment]
Yeah there was an event type filter in the workflow we missed, so pypi release step was skipped, apologies. We'll release 0.5.11 instead

**Comment by edwargix** [comment]
hmm it looks like the `release` job was skipped for 0.5.12 also :( <https://github.com/lidatong/dataclasses-json/actions/runs/5579680066/jobs/10195575073>

**Comment by george-zubrienko** [comment]
@edwargix so 0.5.10 will never be on PyPI, but we have 0.5.12 which includes 0.5.10 ofc :)

**Comment by george-zubrienko** [comment]
![image](https://github.com/lidatong/dataclasses-json/assets/14901777/12d599c7-eb3a-444b-b06d-ff579e4ac59a)

Yeah first time there was another CI issue - all solved now :)

**Comment by george-zubrienko** [comment]
Apologies to everybody for a little mess with CI - but we are happy with it now and project contributors can also manage project releases, so if anyone wants to help out fixing those 97 remaining issues and future ones - more than welcome :)
