### ISSUE TITLE
[BUG] global configuration of encoder/decoder for type T is not used for Optional[T] field

### ISSUE THREAD

**Issue by PJCampi** [lidatong/dataclasses-json#465]
### Description

Let's say I register a custom encoder/decoder for type `T` in the `global_config`. I would expect that a `dataclass` with a field of type `Optional[T]` to use the encoder/decoder registered. Instead I have to manually register the same encoder for the type `Optional[T]` for the encoder to be picked up.
`_user_overrides_or_exts` does not unwrap the optional type.

### Code snippet that reproduces the issue

```
from dataclasses import dataclass
from dataclasses_json import dataclass_json, global_config
from datetime import date
from typing import Optional

global_config.encoders[date] = date.isoformat
# global_config.encoders[Optional[date]] = date.isoformat

@dataclass_json
@dataclass
class DataClassWithIsoDatetime:
    created_at: Optional[date] = None

print(DataClassWithIsoDatetime(date.today()).to_json())
```

### Describe the results you expected

{"created_at": "2023-08-08"}

### Python version you are using

3.9

### Environment description

dataclasses-json==0.5.14

**Comment by george-zubrienko** [comment]
Should be solved in v1, but I suggest we still fix this in v0

**Comment by PJCampi** [comment]
This is becoming a bigger problem for me (global configs are also not applied from collections or mappings) so I will try to see if I can fix this tomorrow. It should be relatively simple.

**Comment by PJCampi** [comment]
I have a fix for the bug. I can create a PR if someone can grant me write access to the repo.

**Comment by PJCampi** [comment]
here you go: https://github.com/lidatong/dataclasses-json/pull/524
