### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dardevelin** [lidatong/dataclasses-json#48]
Hi I saw this package in PIP but there is no license listed. Would you be kind enough to add one ? Maybe MIT ? Thanks

**Comment by lidatong** [comment]
Hi there, the project is actually licensed under `Unlicense` (I realize it might be confusing, because it looks like "unlicensed"). You can read more about it [here](http://unlicense.org/). Let me know if you have more questions

**Comment by dardevelin** [comment]
Unfortunately in German law it is public domain if they have been published
as part of a law or decree or edict otherwise it always belongs the author
until 70 years past his death because it is considered undeclared by the
author.

Kiling public domain ... :/

**Comment by dardevelin** [comment]
Also since there is no single reference for this unlicensed it
automatically falls under protected copyright notice ...

>

**Comment by uriva** [comment]
@lidatong I've sent a pull request to clarify this.

**Comment by lidatong** [comment]
I apologize for dropping this and not getting back to you @dardevelin 

I was ignorant of the legality of Unlicense in different jurisdictions (though I find the situation of not being to un-license a work incredibly ironic...). I'm going to relicense the work as MIT. thanks @uriva for reminding me

**Comment by dardevelin** [comment]
@lidatong thank you very much
