### ISSUE TITLE
datetime.datetime.fromisoformat Compatibility

### ISSUE THREAD

**Issue by HappyTreeBeard** [lidatong/dataclasses-json#52]
The function ```datetime.datetime.fromisoformat(str)``` is [new to Python 3.7](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat) and ```setup.py``` states ``` python_requires=">=3.6"``` The [backports-datetime-fromisoformat](https://pypi.org/project/backports-datetime-fromisoformat/) package on pypi should be added to the package requirements if Python 3.6 is to be supported.

 It looks like the ```fromisoformat``` dependency was added to resolve the ["0.1.0 datetime handling does not conform to iso 8601"](https://github.com/lidatong/dataclasses-json/issues/40) ticket.

**Comment by lidatong** [comment]
Please see explanation in #53
