### ISSUE TITLE
Allow adding custom encoder for certain data types

### ISSUE THREAD

**Issue by smartnose** [lidatong/dataclasses-json#56]
I would like to add custom support for a few data types (such as `date`). There doesn't seem to be a clean extension mechanism in `dataclasses-json`. I see that `_ExtendedEncoder` here supports a few types:
https://github.com/lidatong/dataclasses-json/blob/master/dataclasses_json/core.py#L17-L31

However, we would like to serialize `date` instead of `datetime`. Also, I would like to customize its format.

**Comment by lidatong** [comment]
Docs are updated
