### ISSUE TITLE
Support json to dictionary

### ISSUE THREAD

**Issue by PeterLaudel** [lidatong/dataclasses-json#59]
Hey i really like your dataclass json package. Currently I like to have the feature for remember a json to an dictonary and backwards. An example:

```
MinionId = NewType('MinionId', int)

@dataclass_json
@dataclass
class Minion:
    minion_id: MinionId
    name: str

@dataclass_json
@dataclass
class Datas:
    minions: Dict[MinionId, Minion]
    some_value: int
    some_name: int
```

From the json or to the json:

```
{
    "minions": [
        {
            "minion_id": 1,
            "name": "minion1"
        },
        {
            "minion_id": 2,
            "name": "minion2"
        }
    ],
    "some_value": int,
    "some_name": int
}
```

Maybe there is already an solution to fix this.

**Comment by boisei0** [comment]
If I don't misunderstand your question, you should be able to get the "to dict" part of this question working using the `asdict` function from the standard library:
```
from dataclasses import asdict
# assuming that datas contains your instance of Datas
assert isinstance(asdict(datas), dict)
```
On the other hand, considering this library uses marshmallow internally, you can also use something akin to `Datas.schema().dump(datas)` to get a `NamedTuple`, as [described here in the marshmallow docs](https://marshmallow.readthedocs.io/en/2.x-line/api_reference.html#marshmallow.Schema.dump). To go [from already parsed json to filling the dataclass](https://marshmallow.readthedocs.io/en/2.x-line/api_reference.html#marshmallow.Schema.load) you can do the same with `Datas.schema().load(datas_dict)`. The similar `Datas.schema().loads(datas_json_string)` can be used to load from a string containing the json. Hope that helps.

**Comment by Peilonrayz** [comment]
Your data and classes aren't the same.

 - `[]` is a `typing.List`, `{}` is a `typing.Dict`. 
 - `int` isn't a valid JSON literal and so breaks the parsing.

The library converts to and from just fine with these accounted for.

```
@dataclass_json
@dataclass
class Minion:
    minion_id: int
    name: str

@dataclass_json
@dataclass
class Datas:
    minions: List[Minion]
    some_value: int
    some_name: int


data = '''{
    "minions": [
        {
            "minion_id": 1,
            "name": "minion1"
        },
        {
            "minion_id": 2,
            "name": "minion2"
        }
    ],
    "some_value": 1,
    "some_name": 1
}'''

d = Datas.from_json(data)
print(d)
print(Datas.to_json(d))
```
