### ISSUE TITLE
Promote sharing encoding/decoding across multiple dataclasses

### ISSUE THREAD

**Issue by chrahunt** [lidatong/dataclasses-json#61]
# Problem

The current API only allows providing custom encoder/decoder on a field-by-field basis using metadata. The options for user code are not good:

1. Repeat metadata for each usage of a custom type
2. Define function for each custom type that returns a `dataclasses.Field` instantiated with the metadata

1 is obviously not good. 2 leads to more verbose code, e.g.

```python
@dataclass_json
@dataclass
class Container:
    d: Data = data_field()
    d2: Data = data_field(default=1)
```

given an implementation like

```python
from dataclasses import dataclass, field
from dataclasses_json import dataclass_json

class Data:
    ...

def data_field(**kwargs):
    metadata = kwargs.setdefault('metadata', {})
    metadata.setdefault('dataclasses_json', {
        'encoder': lambda x: None,
        'decoder': Data,
        'mm_type': None
    })
    return field(**kwargs)

```

even in the default case (`d`) we cannot omit the `data_field()`.

# Desired solution

1. Encoder/decoder should be trivial to specify in one place per type with little to no boilerplate in user code
2. Fields within a dataclass that would otherwise not need to use `field()` (e.g. `d: dict = field(default_factory=dict)`) should not have to in order to specify encoder/decoder. In the example above it should look like `d: Data` only.
3. It should be possible to override encoding/decoding of a type for the rendering of several classes while still maintaining 1 and 2.

**Comment by lidatong** [comment]
#139
