### ISSUE TITLE
Library is not compatible with "from __future__ import annotations" (PEP 563)

### ISSUE THREAD

**Issue by chrahunt** [lidatong/dataclasses-json#62]
[PEP 563](https://www.python.org/dev/peps/pep-0563/) means that we cannot expect type annotations to actually be class objects. Example code that fails (Python 3.7):

```python
from __future__ import annotations

from dataclasses import dataclass
from dataclasses_json import dataclass_json


@dataclass
class T:
    f: str

@dataclass_json
@dataclass
class U:
    t: T

obj = U(T('foo'))
print(obj)
s = obj.to_json()
print(s)
obj2 = U.from_json(s)
print(obj2)
```

which outputs

```
U(t=T(f='foo'))
{"t": {"f": "foo"}}
U(t={'f': 'foo'})
```

The expected behavior is that `t` is of type `T` and not a dict. This works as expected when `from future import __annotations__` is commented out.

**Comment by lidatong** [comment]
Hi, yes, I am aware of this issue and it is being tracked in #31, specifically #5. Thanks for reporting.

My instinct is there isn't a good way to address this (as described in #5) without improvements to the `typing` API, but let me know if you have suggestions.

**Comment by chrahunt** [comment]
To get the types we must call [`typing.get_type_hints`](https://docs.python.org/3/library/typing.html#typing.get_type_hints) and passing the class. This returns a mapping that can be used to retrieve the type by passing `field.name`. For example:

```
$ python
Python 3.7.1 (default, Jan  1 2019, 15:19:53)
[GCC 5.5.0 20171010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import annotations
>>> from dataclasses import dataclass, fields
>>> import typing
>>> @dataclass
... class C:
...  i: int
...
>>> fields(C)
(Field(name='i',type='int',default=<dataclasses._MISSING_TYPE object at 0x7f62e8594780>,default_factory=<dataclasses._MISSING_TYPE object at 0x7f62e8594780>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),_field_type=_FIELD),)
>>> fields(C)[0].type
'int'
>>> fields(C)[0].name
'i'
>>> typing.get_type_hints(C)
{'i': <class 'int'>}
>>> typing.get_type_hints(C)[fields(C)[0].name]
<class 'int'>
```

The only caveat with this approach is that for classes that use forward references (with the class name itself) the `typing.get_type_hints` will raise a `NameError` if called before the class has been actually initialized in its module (such as directly in a decorator).
