### ISSUE TITLE
Support all operations on plain dataclasses through functions

### ISSUE THREAD

**Issue by rominf** [lidatong/dataclasses-json#74]
I have an existing codebase and don't want to change my dataclasses. I propose to add functions (not methods) like: `to_json`, `from_json`, etc.

**Comment by Peilonrayz** [comment]
Have you tried replacing `obj.to_json(...)` with `DataClassJsonMixin.to_json(obj, ...)`?

**Comment by rominf** [comment]
Nope. But I don't like this solution as non-obvious and long. It would be better to have them as separate functions, like `dataclasses.asdict` and `dacite.from_dict` (https://github.com/konradhalas/dacite).

**Comment by Peilonrayz** [comment]
A quick google [shows the method I outlined above][0], so I don't think it's 'non-obvious'. Also you can just alias the function, so it's not long.

```python
from dataclasses_json import DataClassJsonMixin

to_json = DataClassJsonMixin.to_json


class MyDataClassJsonMixin(DataClassJsonMixin):
    asdict = DataClassJsonMixin.to_json
```

  [0]: https://stackoverflow.com/a/805091
