### ISSUE TITLE
Union type deserialize to dict from json

### ISSUE THREAD

**Issue by denisvlah** [lidatong/dataclasses-json#82]
The the Union type on a dataclass cannot be deserialized correctly from json.
Example:

```
from dataclasses import dataclass
from dataclasses_json import dataclass_json
from typing import *


@dataclass_json
@dataclass(unsafe_hash=True)
class Gofy:
    p1: str

@dataclass_json
@dataclass(unsafe_hash=True)
class Foo:
    p2: str

@dataclass_json
@dataclass(unsafe_hash=True)
class Agg:
    inst: Union[Gofy, Foo]


if __name__ == '__main__':
    a = Agg(inst=Foo(p2='p2'))
    json_str = a.to_json()
    a_restored = Agg.from_json(json_str)
    print(type(a_restored.inst) ) # this will print the dict type
    assert a == a_restored # this check fails
    assert isinstance(a_restored.inst, Foo) # this check fails
```

**Comment by uriva** [comment]
+1 did you find any solution?

**Comment by denisvlah** [comment]
My workaround is to deserialize json using dataclass-json lib and after that fix with custom code fields that were deserializwd as dict

**Comment by lidatong** [comment]
hi, thanks to @FaraSeer the latest release (0.2.5) supports union types

**Comment by fanchunke1991** [comment]
> hi, thanks to @FaraSeer the latest release (0.2.5) supports union types

the issues mentioned by @denisvlah actually  exists in version 0.3.6

**Comment by obi1kenobi** [comment]
Just got bitten by this in 0.3.7, and confirmed that the original reproduction test case still points out the bug: 2/2 assertions fail. It appears that #93 may have suffered a regression. Would be happy to help if this is something the maintainers feel would be a good first issue for someone entirely unfamiliar with the codebase of this otherwise awesome library.

**Comment by FaraSeer** [comment]
@fanchunke1991, @obi1kenobi, please use the following way:
```python
Agg.schema().dump(a)
a_restored = Agg.schema().load(json_str)
```
instead of
```python
json_str = a.to_json()
a_restored = Agg.from_json(json_str)
```

**Comment by obi1kenobi** [comment]
Thanks for the suggested workaround. Is there an equivalent workaround for converting from/to dict? Unfortunately, by the time my module gets the data, it has already been decoded from JSON and its response needs to be a dict that will (later on) be encoded as JSON elsewhere.

**Comment by meandmymind** [comment]
@lidatong hi! I experience the same issue on 0.4.1. Hack suggested by @FaraSeer solves the problem, but I guess it should be solved generally 😅
