### ISSUE TITLE
ignore unknown properties in nested classes. How to propagate schema config to nested classes?

### ISSUE THREAD

**Issue by arturstorm** [lidatong/dataclasses-json#94]
I want to ignore unknown properties in nested classes when I parse json with unknown(not mapped) fields.
Parsing unknown properties works with `Boss.from_json(boss_json)`. But there a lot of code where It use marshmallow schemas directly like `Boss.schema().loads(boss_json, unknown="exclude")`

How can I define classes with `@dataclass_json` to ignore unknown properties in nested schemas by default?  

```python 
from dataclasses import dataclass
from dataclasses_json import dataclass_json
from typing import List

@dataclass_json
@dataclass(frozen=True)
class Minion:
    name: str


@dataclass_json
@dataclass(frozen=True)
class Boss:
    minions: List[Minion]

boss_json = """
{
    "minions": [
        {
            "name": "evil minion", 
            "UNKNOWN_PROPERTY" : "value"
        },
        {
            "name": "very evil minion"
        }
    ],
    "UNKNOWN_PROPERTY" : "value"
}
""".strip()
Boss.schema().loads(boss_json, unknown="exclude")
```
RESULT:
`marshmallow.exceptions.ValidationError: {'minions': {0: {'UNKNOWN_PROPERTY': ['Unknown field.']}}}`
Expected:
`Boss(minions=[Minion(name='evil minion'), Minion(name='very evil minion')])`

**Comment by nathan5280** [comment]
I've started poking a round with dataclasses-json as a replacement for my homegrown version of this functionality and anticipate running into this issue.  I haven't had a chance to look at how to solve this cleanly, but came up with this work around.  It wouldn't be too hard to do this recursively.

```python
from dataclasses import dataclass
from dataclasses_json import dataclass_json
from typing import List

from marshmallow import EXCLUDE, ValidationError


@dataclass_json
@dataclass(frozen=True)
class Minion:
    name: str


@dataclass_json
@dataclass(frozen=True)
class Boss:
    minions: List[Minion]


boss_json = """
{
    "minions": [
        {
            "name": "evil minion", 
            "UNKNOWN_PROPERTY" : "value"
        },
        {
            "name": "very evil minion"
        }
    ],
    "UNKNOWN_PROPERTY" : "value"
}
""".strip()


def main():
    boss_schema = Boss.schema(unknown=EXCLUDE)
    try:
        boss_schema.loads(boss_json, unknown="exclude")
    except ValidationError:
        pass

    boss_schema.fields["minions"].container.unknown = EXCLUDE
    boss = boss_schema.loads(boss_json)
    print(boss)


if __name__ == "__main__":
    main()
```

Basically what I've done is to generate the Boss Schema and then got in and get the nested Minion Schema and change it's unknown attribute to EXCLUDE.  This now runs cleanly and gets the Expected result.

**Comment by arturstorm** [comment]
@nathan5280, thanks for answer!
It will be grate to have functionality like in Jakson(java lib)   `@JsonIgnoreProperties(ignoreUnknown = true)`:
```python 
@dataclass_json(unknown=EXCLUDE)
@dataclass(frozen=True)
class Minion:
    name: str
```

**Comment by r-richmond** [comment]
At the risk of being too verbose and exposing some potential ignorance, I'd just like to say
1) Awesome project lidatong
2) The functionality arturstorm describes would also be amazing; in my case I'm only interested in some high-level portions of a rest-api response but based on my understanding of the project I had to completely type out the entire response to use `dataclass_json`.

**Comment by RunOrVeith** [comment]
I will submit a pull request for a general solution to this. 
I have it working using the `from_dict` methods, but not the schema yet. But I think I know how to add it there as well, I will look at that tomorrow.

There will be options such as `@dataclass_json(undefined_parameters=UndefinedParameters.IGNORE)` 
`@dataclass_json(undefined_parameters=UndefinedParameters.RAISE)` 
`@dataclass_json(undefined_parameters=UndefinedParameters.CATCH_ALL)` 

The naming of things is still open, I might make use of the marshmallow naming. I'll link the pull request here when I make it.
